### ISSUE TITLE
Compose an overview of the tasks of a node, with a focus on performance

### ISSUE THREAD

**Issue by amesgen** [IntersectMBO/ouroboros-consensus#1057]
For educational purposes (both for onboarding as well as for interested SPOs), we want to compose an overview of the main tasks of a caught-up node, and give a sense of the performance characteristics.

Topics include:

 - What causes the node to do work (leadership checks; incoming new data like headers, blocks, txs; selection changes)
 - Which tasks happen sequentially vs in parallel 
 - Time budgets, in particular known outliers (eg cross-epoch ticking)

We can start at the scope of a single node process and then "zoom out" to embed this information in the the large distributed systems context.

One goal of this is enabling consumers of this new documentation to be in a better position to make an informed choice when it comes to parameter changes (eg block size).

**Comment by nfrisby** [comment]
It might also be useful to subsequently characterize how alterations to some protocol parameters (eg blocksize) would alter this analysis.
