### ISSUE TITLE
[BUG] - db-synthesizer returns `ForgeResult {resultForged = 0}` when trying to append blocks to a network stuck far away in the past

### ISSUE THREAD

**Issue by AngelCastilloB** [IntersectMBO/ouroboros-consensus#1064]
**Internal/External**
*Internal* 

**Summary**

*Some context:* 

In the cardano-js sdk e2e environment we bootstrap a local test network, we create many different kind of transaction to populate its state and wait for four epochs before we start our e2e tests. This whole process takes roughly 25 minutes, we want to speed up this by creating a snapshot of the docker containers after we reach this point, and then just starting the containers from this point (thus skipping the whole setup part). The the nodes don't to produce blocks because some time has passed since we took the snapshot.
So we want to recover the network by appending enough blocks to the old chain, for this we want to use the db-synthesizer tool.

*The issue:*
When trying to run the db-synthesizer we get as result that no blocks were forged:

```
local-network-e2e-local-testnet-1               | --> forger count: 11
local-network-e2e-local-testnet-1               | --> opening ChainDB on file system with mode: OpenAppend
local-network-e2e-local-testnet-1               | --> starting at: SlotNo 4026
local-network-e2e-local-testnet-1               | --> epoch size: EpochSize 1000
local-network-e2e-local-testnet-1               | --> will process until: ForgeLimitSlot (SlotNo 432000)
local-network-e2e-local-testnet-1               | --> forged and adopted 0 blocks; reached SlotNo 436026
local-network-e2e-local-testnet-1               | --> done; result: ForgeResult {resultForged = 0}
```

**Steps to reproduce**
Run the db-synthesizer:

` ./db-synthesizer --config ./config/network/cardano-node/config.json --db ./db  --bulk-credentials-file ./bulk-creds.json -s 100000 -a`

I have attached the a zip file with the db, plus the config files and the bulk credentials: 

[environment.zip](https://github.com/IntersectMBO/ouroboros-consensus/files/15009947/environment.zip)

The version of the db-synthesizer we are using can be obtained from here:

`wget -O bin.tar.gz https://update-cardano-mainnet.iohk.io/cardano-node-releases/cardano-node-1.35.4-linux.tar.gz`

Things we have verified:

**The wrong keys are given:**

We use the `cardano-cli genesis create-staked `to create all the keys, and then we move the to a separate directory per pool:

```
mv "${ROOT}/pools/vrf${NODE_ID}.skey" "${TARGET}/vrf.skey"
mv "${ROOT}/pools/opcert${NODE_ID}.cert" "${TARGET}/opcert.cert"
mv "${ROOT}/pools/kes${NODE_ID}.skey" "${TARGET}/kes.skey"
```
I think this must be the right keys, since the network works correctly and the pools can mint new blocks when we start it from scratch.

**The pool keys given are correct, but KES for those keys has expired:**

This is the `cardano-cli query kes-period-info` of the keys, they all have the same info:

```
CARDANO_NODE_SOCKET_PATH=./network-files/node-sp1/node.sock ./bin/cardano-cli query kes-period-info --testnet-magic 888 --op-cert-file ./network-files/node-sp2/opcert.cert
✓ Operational certificate's KES period is within the correct KES period interval
✓ The operational certificate counter agrees with the node protocol state counter
{
    "qKesCurrentKesPeriod": 0,
    "qKesEndKesInterval": 60,
    "qKesKesKeyExpiry": null,
    "qKesMaxKESEvolutions": 60,
    "qKesNodeStateOperationalCertificateNumber": 0,
    "qKesOnDiskOperationalCertificateNumber": 0,
    "qKesRemainingSlotsInKesPeriod": 7771882,
    "qKesSlotsPerKesPeriod": 129600,
    "qKesStartKesInterval": 0
}
```

**We have forked to Conway era:** 

Our local network is still in Babbage era:

```
CARDANO_NODE_SOCKET_PATH=./network-files/node-sp1/node.sock ./bin/cardano-cli query tip --testnet-magic 888
{
    "block": 442,
    "epoch": 4,
    "era": "Babbage",
    "hash": "2a527b8f0658d76e38bcc5813417532bcab50712eded0fb9b686fd7a2480f535",
    "slot": 4118,
    "syncProgress": "0.89"
}
```

**Expected behavior**
Blocks are added to the chain. And if the correct amount of blocks are added, we can recover the network.

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version: 20.04
- Consensus version: I am not sure, but the tool we are using comes bundled with the 1.35.4 version of cardano-node: https://update-cardano-mainnet.iohk.io/cardano-node-releases/cardano-node-1.35.4-linux.tar.gz

**Screenshots and attachments**
[environment.zip](https://github.com/IntersectMBO/ouroboros-consensus/files/15009947/environment.zip)

**Additional context**
We are logging this as a bug, but honestly we are not sure if it is an issue in the tool or our environment, but we have ran out of ideas and there are no errors to go from.

**Comment by dnadales** [comment]
@AngelCastilloB Thank you for reporting. Could you check if [this configuration option](https://github.com/IntersectMBO/ouroboros-consensus/issues/1071#issuecomment-2069579096) would solve your problem?
