### ISSUE TITLE
Update to `nothunks-0.2.1.0`

### ISSUE THREAD

**Issue by coot** [IntersectMBO/ouroboros-consensus#1190]
`nothunks-0.2.1.0` is available on `hackage`; Future version of `ouroboros-network` will depend on it.  Could you update the packages:

* `ouroboros-consensus`
* `strict-sop-core`
* `sop-extras`

Which now have a constraint `nothunks ^>= 0.1`.

**Comment by dnadales** [comment]
Waiting on Plutus to release [these changes](https://github.com/IntersectMBO/plutus/pull/6349/files) to CHaP.

**Comment by dnadales** [comment]
This seems to be the Plutus PR we need (plus a corresponding CHaP PR).

**Comment by dnadales** [comment]
Should be fixed once [this branch](https://github.com/IntersectMBO/ouroboros-consensus/compare/jordan/bump-plutus-1.32-and-ledger) is merged.
