### ISSUE TITLE
[BUG] - "Unable to find a truncate point" with slot based truncation

### ISSUE THREAD

**Issue by johnalotoski** [IntersectMBO/ouroboros-consensus#1202]
**Internal/External**
*Internal*

**Summary**
DB truncating by slot seems to frequently throw the following error, even when the slot given should be within the immutable range:
```
Unable to find a truncate point. This is because the ImmutableDBdoes not contain a block with the given slot or block number.
```

This message started with the db-truncater bundled with node from a few node versions ago, possibly around node `8.10` or `8.11`.  At the time, just adjusting the requested truncation slot lower to an earlier epoch (or two or three) would solve the problem.

However, with the latest db-truncater bundled with node 9.1, testing on a preview chain, most attempted valid slot given to db truncater seems to immediately throw this error.

While db truncating by block seems to behave normally, truncating by slot is more convenient for calculation purposes, for example, if truncation to the start of a specific epoch is desired.

**Steps to reproduce**
1) Get db state to test on, example `preview` network
2) Run db-analyser on the db state:
```bash
❯ db-analyser   --db "$DATA_DIR/db"   cardano   --config "$DATA_DIR/config.json"
[312.466036s] Started OnlyValidation
[312.466229s] Done
ImmutableDB tip: At (Block {blockPointSlot = SlotNo 55860676, blockPointHash = 0a1d3e4668b8703a28221655d2328c24e1e556e6e15abb6f845816fdaff9098a})
```
3) Try truncation by slot.  Try several, starting with a valid immutable slot lower than the immutable tip slot shown above in the db-analyser output and backing down the slot value on each failure until we succeed:
```bash
❯ db-truncater  --db "$DATA_DIR/db"  --truncate-after-slot 55800000  cardano  --config "$DATA_DIR/config.json"
Unable to find a truncate point. This is because the ImmutableDBdoes not contain a block with the given slot or block number.

# Try again with slot 55000000, same error
# Try again with slot 50000000, same error
# Try again with slot 40000000, same error
# Try again with slot 10000000, same error

# Try again with slot 1000, success!
❯ db-truncater  --db "$DATA_DIR/db"  --truncate-after-slot 1000  cardano  --config "$DATA_DIR/config.json"

❯ db-analyser   --db "$DATA_DIR/db"   cardano   --config "$DATA_DIR/config.json"
[0.072284s] Started OnlyValidation
[0.072533s] Done
ImmutableDB tip: At (Block {blockPointSlot = SlotNo 1000, blockPointHash = 8f20b5378629cc15e78edf6084c2eb75cd1698074abdb6f422ed6ed195b4314e})
```

To contrast the above, truncating by block number works on the first attempt.  Maybe I've just gotten lucky the few times I've tested with block truncation vs. slot truncation, but block truncation doesn't seem to have the same problem AFAIK.  The follow up db-analyser shows the immutable tip is close to the specified truncation block.
```
❯ db-truncater  --db "$DATA_DIR/db" --truncate-after-block 2000000 cardano  --config "$DATA_DIR/config.json"

❯ db-analyser   --db "$DATA_DIR/db"   cardano   --config "$DATA_DIR/config.json"
[254.084486s] Started OnlyValidation
[254.084728s] Done
ImmutableDB tip: At (Block {blockPointSlot = SlotNo 46755827, blockPointHash = 275a9e21c2a0bc557196cf196866d09d5b960d770e6cfaa4d98e90160b514234})
```

**Expected behavior**
Truncation at the specified valid slot which is present in immutable files per db-analyser reported immutable slot tip.

**System info (please complete the following information):**
- OS Name: `NixOS`
- OS Version: `24.05`
- Consensus version: `db-truncater from node 9.1 flake, package marked as version 0.18.0.0`

**Comment by amesgen** [comment]
This is due to #1143, in particular 5747d3c76f3a2a73635f010f568cef1c4724b32f, which made truncation constant time instead of linear time (in the number of blocks until the truncation cutoff), but also comes with a change in behavior:
```
db-truncater: make slot truncation constant-time

This also slightly changes the semantics: Previously, it would truncate to the
block with the largest slot that is smaller or equal to the slot argument. Now,
it will only truncate to the (non-EBB) block in exactly that slot, and fail
otherwise.

In fact, the new behavior more closely corresponds to the CLI description:

  --truncate-after-slot SLOT_NUMBER
                           The slot number of the intended new tip of the chain
                           after truncation
```

So the problem in the examples you give above is that there is no block with e.g. exactly slot number 55000000 in the `preview` db (nearest blocks are in slot `54999994` and `55000001`). That's why the error message says that the db "does not contain a block with the given slot [...] number."

Now the question is: Is this new behavior very inconvenient for you, or is it not a problem now that it is clear what is going on? It should be straightforward to bring back the old behavior behind a flag. Sorry that I didn't check with you in advance!

**Comment by johnalotoski** [comment]
Thank you for the explanation and clearing up my confusion!  I don't run the truncate command very often so scanning sequentially to find the closest valid slot to a desired target won't pose a problem.  Also it's nice to have constant time with the command now, thank you!

**Comment by amesgen** [comment]
The more I think about, the more I like the previous behavior of `--truncate-after-slot`. I opened #1203 to restore it as it is a really small change. You can get a corresponding `db-truncater` via
```
nix build github:IntersectMBO/ouroboros-consensus/amesgen/db-truncater-clip-slot#db-truncater
```
