### ISSUE TITLE
[FEAT] - New ledger state queries

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/ouroboros-consensus#1204]
**Internal**

**Describe the feature you'd like**
We need to add some queries.

New Conway ledger state queries have been requested and already implemented in ledger: https://github.com/IntersectMBO/cardano-ledger/pull/4514

* [`queryProposals`](https://github.com/IntersectMBO/cardano-ledger/blob/411054e40b4e08350049e4eaffdf0cc5f73e9d91/libs/cardano-ledger-api/src/Cardano/Ledger/Api/State/Query.hs#L328-L334)
* and `queryRatifyState`](https://github.com/IntersectMBO/cardano-ledger/blob/411054e40b4e08350049e4eaffdf0cc5f73e9d91/libs/cardano-ledger-api/src/Cardano/Ledger/Api/State/Query.hs#L346C1-L347)

Also there is another query that has been implemented that should be added, which works for all eras, not only Conway:

* [`queryFuturePParams`](https://github.com/IntersectMBO/cardano-ledger/blob/411054e40b4e08350049e4eaffdf0cc5f73e9d91/libs/cardano-ledger-api/src/Cardano/Ledger/Api/State/Query.hs#L317-L321)

**Describe alternatives you've considered**

I've considered implementing them myself, but decided to create this ticket instead :wink: 

**Additional context / screenshots**

**Comment by dnadales** [comment]
`GetProposals` and `GetRatifyState` were added in [this commit](https://github.com/IntersectMBO/ouroboros-consensus/commit/0f10c19d77bc72ba0fcc009d0e80b4ac2258d33c).

It seems we still need to add the `queryFuturePParams` query.

**Comment by dnadales** [comment]
Closed by #1251
