### ISSUE TITLE
Release `ResourceRegistry` as a standalone package in Hackage

### ISSUE THREAD

**Issue by jasagredo** [IntersectMBO/ouroboros-consensus#1277]
The `ResourceRegistry` module is a separate, standalone piece of functionality that is useful on its own. It keeps track of lifetimes of resources and ensures proper release of them. This is generally useful in the wider Haskell ecosystem.

We want to release it to Hackage as a standalone package. However there are several questions to resolve:

- We would prefer if this is a separate repository from `ouroboros-consensus`. Should this repository live in `IntersectMBO` or in `input-output-hk`?
- Who should be the copyright holder? Currently in `ouroboros-consensus` it is `2019-2023 Input Output Global Inc (IOG), INTERSECT 2023-2024`.
- Who should upload this package to Hackage? the [IOHK](https://hackage.haskell.org/user/IOHK) user?

Note that this package has not changed in ~3 years, and that the original authors no longer work with us, but developed it for `IOHK`.

**Comment by jasagredo** [comment]
Please let us know your preferences on this matter @ThatGuyLLC. We would like to split this off from Consensus as soon as we give green light.

**Comment by kevinhammond** [comment]
I'd be inclined to say IO should do this if it agrees rather than Intersect.  Rationale: it's a generally useful package rather than something which is Cardano-specific.  But if it's critical to Cardano, then it absolutely ought to be sponsored by Intersect

**Comment by jasagredo** [comment]
It is a piece of functionality the Cardano implementation relies on, as any other library we use from Hackage. But it is not only cardano-specific (like some custom Cardano addresses parser library would be for example)

**Comment by ThatGuyLLC** [comment]
After consulting with multiple relevant parties, I recommend we host it under Intersect and drive its development as a resource not limiting us to just Cardano specific functions. So a separate repo here makes sense and we can work out the set-up.
Now uploading to Hackage, I have not done before and might follow the same process for now or happy to be taught how we can do this as Intersect, first-time for everything.
I think that copyright listed is accurate.

**Comment by amesgen** [comment]
Done via #1291
