### ISSUE TITLE
Address partiality of `applyDistribLedgerTables`

### ISSUE THREAD

**Issue by jasagredo** [IntersectMBO/ouroboros-consensus#144]
`applyDistribLedgerTables` is partial. If we try to project into `Allegra` tables that have entries for `Alonzo` it will fail. This won't happen in absence of consensus bugs, but we might want to make this explicit and fail the query instead of killing the node with an error.

**Comment by jorisdral** [comment]
I've been looking into this, but I haven't come up with a plan on how to address the partiality. For the time being, I don't think it's problematic to keep the code as is

**Comment by jorisdral** [comment]
Blocked on #261
