### ISSUE TITLE
Investigate whether `DbChangelog.flush` should split diff sequences by some metric other than length.

### ISSUE THREAD

**Issue by jorisdral** [IntersectMBO/ouroboros-consensus#208]
Originally from https://github.com/input-output-hk/ouroboros-network/pull/4343#discussion_r1102706450. We consider the `DbChangelog` module in this issue.

The `flush` function currently flushes differences to disk based on the length of the diff sequence that we take the differences from. However, we should investigate if we should some other metric, like `Point` to split the diff sequence: the length of the diff sequence does not necessarily coincide with progression of time/slots/points on the blockchain.

```haskell
    -- TODO #4371 by point, not by count, so sequences can be ragged
    splitSeqDiff ::
         (Ord k, Eq v)
      => SeqDiffMK k v
      -> (SeqDiffMK k v, SeqDiffMK k v)
    splitSeqDiff (SeqDiffMK sq) =
        bimap SeqDiffMK SeqDiffMK
      $ splitAt (AS.length imm) sq
```

**Comment by jasagredo** [comment]
I don't see any particular reason why other metric should be used. We know the length of the sequence of states, in particular we know how many "immutable states" must have a corresponding difference in the diffseq, then we can just split at the given length. I don't see why this could fail

**Comment by jorisdral** [comment]
I don't think it's about whether it could fail, but if it would be a better alternative. However, I think the way we're doing it now is how it should be done: always flush all the diffs that are in the immutable part of the changelog.

**Comment by jorisdral** [comment]
Closing this issue, because we're not changing the flushing approach
