### ISSUE TITLE
Get UTxO-HD ready for handover

### ISSUE THREAD

**Issue by dnadales** [IntersectMBO/ouroboros-consensus#28]
We aim at producing a UTxO-HD enabled node that meets the performance requirements of all the stakeholders, and that passes the system-level tests. Successfully achieving this means we will have a version ready to be tested on a production environment (testnet and mainnet).

The UTxO-HD feature should be ready for production testing, which means:

- [x] #205 
- [x] #314
- [x] #227
- [x] ~#429~
- [x] #510
- [x] #815 
- [x] Implement LedgerDB V2
- [x] #203
- [x] #188
- [ ] The prototype implementation will be handed over for testing on testnet (by signalling readiness to @disassembler).
- [ ] Notify the following downstream clients about the upcoming release:
    - [ ] Mithril 
    - [ ] Wallet
    - [ ] Db-sync

Note that merging the UTxO-HD feature branch into `main` depends on whether this blocks other workstreams.

# Risks 

- System level benchmarks might show regressions we have to eliminate.
- Integration tests might find errors we have to fix.

**Comment by jasagredo** [comment]
Benchmarking and testing (on 8.2.0):
- input-output-hk/cardano-node#5441
- input-output-hk/cardano-api#195
- input-output-hk/ouroboros-consensus#260

Up to date versions (on 8.2.1):
- input-output-hk/cardano-node#5416
- input-output-hk/cardano-api#161
- input-output-hk/ouroboros-consensus#260

**Comment by jasagredo** [comment]
UTXO-HD is ready for handover except if Benchmarks shows otherwise. Closing for now, will open a different issue with results if needed.
