### ISSUE TITLE
Uniform git tags and branches for releases

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/ouroboros-consensus#306]
* The `ReleaseProcess.md` document says we create tags `release-FOO-A.B.C`. (I followed this for yesterday's release and plan to for today's too.)
* @fraser-iohk  's tags were just `FOO-A.B.C`, eg `c50490f52 - (tag: ouroboros-consensus-protocol-0.5.0.4, tag: ouroboros-consensus-diffusion-0.7.0.0, tag: ouroboros-consensus-cardano-0.7.0.0, tag: ouroboros-consensus-0.9.0.0) ...`

* @amesgen ’s tags before that were mix of `FOO-A.B.C` and also synonyms without the `ouroboros-consenssus-` prefix: `143e9df61 - (tag: protocol-0.5.0.2, tag: ouroboros-consensus-protocol-0.5.0.2, tag: ouroboros-consensus-diffusion-0.6.0.0, tag: ouroboros-consensus-cardano-0.6.0.0, tag: ouroboros-consensus-0.7.0.0, tag: diffusion-0.6.0.0, tag: consensus-0.7.0.0, tag: cardano-0.6.0.0) ...`

In our scripts:

* https://github.com/input-output-hk/ouroboros-consensus/blob/main/scripts/release/tag-release.sh does a middle ground. It uses `release-` but it drops the `ouroboros-consensus-` prefix where possible.

* https://github.com/input-output-hk/ouroboros-consensus/blob/main/scripts/release/create-release.hs is creating tags (and branches), but in some sense I don't think it should be: tags (and branches) should only point at the result of merged PRs, whereas this script is primarily intended to create the PR... so there's no way it can already know the correct hash for the tags (and branches).

Q1) What do we actually want?

My raw intuition is that we fundamentally want `release/ouroboros-consensus-cardano-0.8.0.0` for example. However, slashes are a _little_ less likely than dashes to be extremely broadly supported. Hence the template I used in the `ReleaseProcess.md`: `release-FOO-A.B.C` (reminder, in that document, `A` stands for `MAJOR.MAJOR` in the context of the PVP).

Q2) If we agree on that, do we want to clean-up our existing tags (and branches)?

**Comment by nfrisby** [comment]
cc @dnadales @jasagredo

**Comment by nfrisby** [comment]
We chatted about this in the stand-up. The decision (only @fraser-iohk was absent) was to adopt `release-FOO-A.B.C` uniformly.

I have done so for the latest commit and retroactively for all existing tags I found.

All tags shown at https://github.com/input-output-hk/ouroboros-consensus/tags now start with `release-...` and my local repo, after issuing `git fetch origin --tags` shows the following.

```
$ git tag --list
release-ouroboros-consensus-0.10.0.0
release-ouroboros-consensus-0.10.0.1
release-ouroboros-consensus-0.5.0.0
release-ouroboros-consensus-0.6.0.0
release-ouroboros-consensus-0.7.0.0
release-ouroboros-consensus-0.8.0.0
release-ouroboros-consensus-0.9.0.0
release-ouroboros-consensus-cardano-0.5.0.0
release-ouroboros-consensus-cardano-0.5.0.1
release-ouroboros-consensus-cardano-0.6.0.0
release-ouroboros-consensus-cardano-0.6.1.0
release-ouroboros-consensus-cardano-0.7.0.0
release-ouroboros-consensus-cardano-0.8.0.0
release-ouroboros-consensus-cardano-0.8.0.1
release-ouroboros-consensus-diffusion-0.5.0.0
release-ouroboros-consensus-diffusion-0.5.1.0
release-ouroboros-consensus-diffusion-0.6.0.0
release-ouroboros-consensus-diffusion-0.6.1.0
release-ouroboros-consensus-diffusion-0.7.0.0
release-ouroboros-consensus-diffusion-0.7.1.0
release-ouroboros-consensus-diffusion-0.7.1.1
release-ouroboros-consensus-protocol-0.5.0.0
release-ouroboros-consensus-protocol-0.5.0.1
release-ouroboros-consensus-protocol-0.5.0.2
release-ouroboros-consensus-protocol-0.5.0.3
release-ouroboros-consensus-protocol-0.5.0.4
release-ouroboros-consensus-protocol-0.5.0.5
release-ouroboros-consensus-protocol-0.5.0.6
```

**Comment by nfrisby** [comment]
I opened PRs #311 and #312.

**Comment by jasagredo** [comment]
Closed as done. The PRs were merged but this didn't close
