### ISSUE TITLE
Abstraction for creating `ProtocolInfo blk` from `ProtocolParams blk`

### ISSUE THREAD

**Issue by jorisdral** [IntersectMBO/ouroboros-consensus#317]
See https://github.com/input-output-hk/ouroboros-consensus/pull/282#discussion_r1290236896

**Comment by nfrisby** [comment]
FYI, I opened https://github.com/input-output-hk/ouroboros-consensus/issues/324 and assigned it to you, because I think it's related. HTH.

**Comment by amesgen** [comment]
`ProtocolParams` will be removed in #1224, so I think this can also be closed by #1224.

**Comment by dnadales** [comment]
This can be closed, as pointed out by @amesgen and confirmed by @jorisdral.
