### ISSUE TITLE
Improve `protocolInfoCardano`

### ISSUE THREAD

**Issue by jorisdral** [IntersectMBO/ouroboros-consensus#319]
This issue lists the different steps taken towards improving the `protocolInfoCardano` function

- [x] #275
- [x] #276
- [x] #317 
- [x] #318
- [x] Rename `ProtocolVersion` to `SupportedProtocolVersion` or something similar, since the name has often caused confusion.
- [x] Encode the invariant that protocol versions should be strictly increasing (except for the last era).
- [x] #324 
- [x] https://github.com/input-output-hk/cardano-ledger/issues/3682

**Comment by amesgen** [comment]
FTR: There have been some changes to `protocolInfoCardano` in #377 due to the new `TransitionConfig` concept from Ledger.

**Comment by dnadales** [comment]
@amesgen, when you have time, we should discuss the remaining item in this issue and whether we can close it, as I don't see a sensible renaming.

**Comment by dnadales** [comment]
As discussed out-of-band with @amesgen, with [1224](https://github.com/IntersectMBO/ouroboros-consensus/pull/1224), creating a separate type is no longer necessary.
