### ISSUE TITLE
Draft a blogpost about UTxO-HD and its impact on performance

### ISSUE THREAD

**Issue by dnadales** [IntersectMBO/ouroboros-consensus#327]
UTxO-HD will have an impact on the Cardano node performance for no apparent immediate benefit. We need to:

- Explain why UTxO-HD is important for the long-term sustainability of the Cardano node.
- Warn about the expected performance loss. 
- Explain the problem and solution 
- Implications of not solving the problem, in particular, what would the mem requirements be. 
- Explain what this means for sustainability and decentralisation. 

We need performance metrics so that the community can make an informed decision. 

We will relay this information in the form of a *draft* blogpost to the Cardano Steering Committee.

**Comment by jasagredo** [comment]
Closing as included in https://github.com/IntersectMBO/ouroboros-consensus/issues/126
