### ISSUE TITLE
[FEAT] - design a lightweight checkpointing mechanism

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/ouroboros-consensus#388]
Even once Ouroboros Genesis is released, "disasters" or "inexplicably lucky" attackers may give rise to scenarios where a lightweight checkpointing mechanism would be useful. Notably, the mere existence of such a mechanism might even itself make the attack vector less attractive.

This Issue is to design such a mechanism.

At this point, the rough idea is that some configuration file could contain a list of points (ie pairs of a slot and a hash) that overrides normal chain comparison and/or validation in some way. The fundamental candidates are: EITHER a header/block whose point is in the list is considered invalid by fiat OR all headers/blocks in the same slot as one of the points but with a different hash are considered invalid by fiat.

---

This is explicitly _not_ a heavyweight checkpointing mechanism, eg once that would give rise to a new and distinct _genesis block_.

**Comment by nfrisby** [comment]
So far I've received feedback wondering if Mithril supplants this. I look forward to learning more about Mithril during the Consensus Office hours next week (2023 Oct 12), after which I can hopefully compare and contrast them here.

**Comment by amesgen** [comment]
Duplicate of #449
