### ISSUE TITLE
Implement legacy mode for UTxO-HD to keep baseline performance

### ISSUE THREAD

**Issue by dnadales** [IntersectMBO/ouroboros-consensus#429]
- [x] https://github.com/input-output-hk/ouroboros-consensus/issues/344
- [ ] Benchmark and test legacy mode.
- [ ] Add Consensus tests for the legacy block.
- [ ] Implement support in node for switching modes.
- [ ] Adapt to documentation to account for legacy mode.

**Comment by dnadales** [comment]
The legacy mode involves code duplication, requires several weeks of work before it is production-ready (more integration and testing). Moreover, we will not release UTxO-HD before Conway to avoid the risks of delaying the latter. 

On the other hand, to integrate the LSM-tree backend for UTxO-HD we need to redesign the Consensus storage layer, and this new design might enable us to implement an alternative in-memory backing store that will have a very similar performance and resource requirements as the current Cardano node.
Therefore, during the coming months, we will focus our efforts on the redesign of the storage layer and the LSM-tree backend.

**Comment by jasagredo** [comment]
Close as won't do
