### ISSUE TITLE
Specify Lightweight Checkpointing

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/ouroboros-consensus#447]
A subsequent ticket should compare and contrast this with Mithril.

This Issue is to specify the motivations and requirements for a lightweight checkpointing scheme. By _lightweight_, we mean that it does not replace any of the work today's node would normally do while syncing the chain and it requires only minimal changes to the node.

**Comment by nfrisby** [comment]
Very rough sketch: For a given point SLOT HASH, an incoming block in a slot >=SLOT is invalid unless its hash equals HASH or a predecessor of it does.

**Comment by nfrisby** [comment]
We think a block- and/or protocol-combinator (a la `ModChainSel` eg) would be the conceptually correct way to implement this.

**Comment by amesgen** [comment]
Closed by #898, see the approach described there
