### ISSUE TITLE
The ouroboros-consensus test library should not depend on Plutus etc

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/ouroboros-consensus#517]
As of PR https://github.com/input-output-hk/ouroboros-consensus/pull/49, the `TreeDiff` module is coming in via the `cardano-ledger-binary` package.

But that package unfortunately depends on Plutus, eg. This significantly increases the dependency tree of the `ouroboros-consensus` tests, which leads to some "inflated" build times.

The upstream `TreeDiff` module is quite simple, so I'm hoping we can relieve this with some small amount of effort (maybe an upstream PR to put that module in a package with fewer dependencies?) (maybe just change our import back to what it was before?).

**Comment by amesgen** [comment]
Similar to #108

**Comment by jasagredo** [comment]
This will be accomplished by #857
