### ISSUE TITLE
Ignore the VRF tiebreaker when the slots are too far apart

### ISSUE THREAD

**Issue by nfrisby** [IntersectMBO/ouroboros-consensus#524]
From comment https://github.com/input-output-hk/ouroboros-network/issues/2913#issuecomment-1781407345

aka "Duncan's tiebreaker"

**Comment by nfrisby** [comment]
It's not obvious what "too far apart" should mean. But Duncan proposed something on the order of $Delta$, since a block Y that is $Delta$ slots after a block X should have extended X instead of competing with it.

**Comment by amesgen** [comment]
This requires #939 as this chain order is intransitive, see #891.
