### ISSUE TITLE
Make `ioToFsError` OS specific

### ISSUE THREAD

**Issue by kderme** [IntersectMBO/ouroboros-consensus#789]
Since windows and unix sometimes throw different kind of Exceptions, on https://github.com/input-output-hk/ouroboros-network/issues/285 we made the equality check too lenient (always true). This can be improved. @Edsko commented https://github.com/input-output-hk/ouroboros-network/pull/530#discussion_r285454081:
```
It would be nice to be a little bit more precise here (as precise as we can be without making MockFS OS 
dependent I guess). But this can be done in a separate PR.

Concretely: let's replace FsIllegalOperation, FsResourceInappropriateType and FsInvalidArgument by a 
more general FsInvalidOperation, and then introduce a Posix and Windows specific ioToFsError function. 
Ideally we'd not bundle FsInsufficientPermissions in there though, so if you do try this and find some 
problems with that, let's think about the specific problems there.
```

**Comment by jorisdral** [comment]
Closing in favour of https://github.com/input-output-hk/fs-sim/issues/45
