### ISSUE TITLE
[FEAT] - Integrate `GetAccountStateQuery` from ledger API

### ISSUE THREAD

**Issue by Soupstraw** [IntersectMBO/ouroboros-consensus#870]
**Internal**

**Describe the feature you'd like**
We added a query for getting the account state to the ledger API. This query should be integrated into consensus once the PR is merged in ledger.

**Additional context / screenshots**
IntersectMBO/cardano-ledger#3977

**Comment by amesgen** [comment]
Resolved by https://github.com/IntersectMBO/ouroboros-consensus/pull/1083
