### ISSUE TITLE
[FEAT] - Integrate initial DReps and DRepsDelegs registrations

### ISSUE THREAD

**Issue by jasagredo** [IntersectMBO/ouroboros-consensus#871]
We were informed by the Ledger Team that [they have implemented](https://github.com/IntersectMBO/cardano-ledger/pull/3951) a way to inject the initial DReps and DRepsDelegs. This should be used in the same way as we are registering initial funds and staking right now (see [this](https://github.com/IntersectMBO/ouroboros-consensus/blob/4fdded6bd8696d9cb8067bb34b9115eb2c0dbe4c/ouroboros-consensus-cardano/src/ouroboros-consensus-cardano/Ouroboros/Consensus/Cardano/Node.hs#L1051-L1052)).

**Comment by dnadales** [comment]
Done in https://github.com/IntersectMBO/ouroboros-consensus/pull/894.
