### ISSUE TITLE
Experiment with `db-analyzer` on the UTxO-HD branch

### ISSUE THREAD

**Issue by jasagredo** [IntersectMBO/ouroboros-consensus#911]
We should use `db-analyzer`/`beacon` to analyze the performance of:
- `main` vs `V2 in-memory`
- `V1 in-memory` vs `V2 in-memory`
- Optional: `main` vs `V1 in-memory`

**Comment by dnadales** [comment]
We're putting this on hold until we get results from P&T. Consider re-opening this issue if it would help to shed light on potential performance regressions.
