### ISSUE TITLE
Integrate Conway-governance into HFC transitions

### ISSUE THREAD

**Issue by dnadales** [IntersectMBO/ouroboros-consensus#920]
Integration should be straightforward once the Ledger team has implemented functionality for answering what the epoch of the next era is (which might be determined by a governance action or certain conditions specific to Conway).

Relevant Ledger ticket: https://github.com/IntersectMBO/cardano-ledger/issues/4006

**Comment by amesgen** [comment]
We also have #60 and #61 about this

**Comment by amesgen** [comment]
This was done in https://github.com/IntersectMBO/ouroboros-consensus/pull/1078
