### ISSUE TITLE
[BUG] - Reenable roundtrip tests for cardano-ledger ledger state and extended ledger state for the next release

### ISSUE THREAD

**Issue by aniketd** [IntersectMBO/ouroboros-consensus#950]
**Internal**

**Summary**
https://github.com/IntersectMBO/cardano-ledger/pull/4072 fixes https://github.com/IntersectMBO/cardano-ledger/issues/3740 and so the [mentioned failing roundtrip tests](https://github.com/IntersectMBO/ouroboros-consensus/blob/a6e6707974d12fecd40650e6fb995d2058772d37/ouroboros-consensus/src/unstable-consensus-testlib/Test/Util/Serialisation/Roundtrip.hs#L764) for ledger state and extended ledger state can be reenabled once we bump the dependency to `cardano-ledger-shelley-test-1.3.0.2`.

**Note**
This change also affects any related golden tests, so their expectations would almost most likely need to be updated.

**Comment by dnadales** [comment]
Thank you, Aniket! :raised_hands:
