### ISSUE TITLE
[FEAT] - Implement relationship between `ChurnModeBulkSync` and `LedgerStateJudgement`

### ISSUE THREAD

**Issue by bolt12** [IntersectMBO/ouroboros-consensus#958]
**Internal**

**Describe the feature you'd like**
It would be ideal that `ChurnModeBulkSync` to be related to `LedgerStateJudgement`. E.g. It would be nice if `TooOld` meant `BulkSync`. Currently `BulkSync` is when we are more than 1000 slots from the tip.

**Comment by bolt12** [comment]
I have implemented it at: https://github.com/IntersectMBO/ouroboros-consensus/commit/43898dce6831ee6768ed49c376ea7f57bae54926 and integrated it at https://github.com/IntersectMBO/ouroboros-consensus/commit/43898dce6831ee6768ed49c376ea7f57bae54926

**Comment by amesgen** [comment]
> I have implemented it at: [43898dc](https://github.com/IntersectMBO/ouroboros-consensus/commit/43898dce6831ee6768ed49c376ea7f57bae54926) and integrated it at [43898dc](https://github.com/IntersectMBO/ouroboros-consensus/commit/43898dce6831ee6768ed49c376ea7f57bae54926)

I guess you didn't intend to link to the same commit twice?

**Comment by bolt12** [comment]
Right, I have fixed that

**Comment by nfrisby** [comment]
Would you open a Consensus PR using the commit you made? The basic logic in it seems appropriate to me.
